### ISSUE TITLE
Some functions cannot find

### ISSUE THREAD

**Issue by GTROB** [xuelang-wang/Paper-code-implementation#2]
invariant_error，TerminalSet_and_Penalty，运行程序时找不到，工具包我都安装了，请问这些函数是包含在哪些文件呢，麻烦大佬指点指点

**Comment by lnshhongbin** [comment]
invariant_error，TerminalSet_and_Penalty，运行程序时找不到，如果可以公开，请发到我的邮箱lnshhongbin@163.com，谢谢

**Comment by xuelang-wang** [comment]
参考#1

**Comment by ningwak** [comment]
> 参考#1

Hi, it seems that the quoted issue doesn't contain the needed information. It's empty now. Could you provide an answer again? Thank you very much.

**Comment by xuelang-wang** [comment]
@lxpr @GTROB 源文件已提交

**Comment by xuelang-wang** [comment]
@lnshhongbin 已提交

**Comment by lnshhongbin** [comment]
Thank you
